"""init_db

Revision ID: 1ee58dca31f8
Revises: 
Create Date: 2025-12-14 03:37:09.469726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee58dca31f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_gatewaykey')
    op.drop_table('_modelmap')
    op.drop_table('_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_provider',
    sa.Column('name', sa.VARCHAR(length=17), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=209), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=32), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.VARCHAR(length=6), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_modelmap',
    sa.Column('source_model', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('target_model', sa.VARCHAR(length=1), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True)
    )
    op.create_table('_gatewaykey',
    sa.Column('key', sa.VARCHAR(length=22), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=15), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('is_hidden', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
