"""add rate_limit and usage_limit to GatewayKey

Revision ID: ca45bf7f827a
Revises: 
Create Date: 2025-12-14 13:39:24.081486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca45bf7f827a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gatewaykey', sa.Column('rate_limit', sa.Integer(), nullable=True))
    op.add_column('gatewaykey', sa.Column('usage_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gatewaykey', 'usage_limit')
    op.drop_column('gatewaykey', 'rate_limit')
    # ### end Alembic commands ###
