"""add request_log table

Revision ID: d8d80ad1a24e
Revises: ca45bf7f827a
Create Date: 2025-12-17 02:19:19.247175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8d80ad1a24e'
down_revision: Union[str, Sequence[str], None] = 'ca45bf7f827a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requestlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestlog_model'), 'requestlog', ['model'], unique=False)
    op.create_index(op.f('ix_requestlog_status'), 'requestlog', ['status'], unique=False)
    op.create_index(op.f('ix_requestlog_timestamp'), 'requestlog', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requestlog_timestamp'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_status'), table_name='requestlog')
    op.drop_index(op.f('ix_requestlog_model'), table_name='requestlog')
    op.drop_table('requestlog')
    # ### end Alembic commands ###
